/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author Napapol
 */
public class Report extends javax.swing.JFrame {

    /**
     * Attributes
     */
    
    String report_type = "";
    
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        
        report_type = "selling";
        
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        
        try {
            MySQLAccess data_table = new MySQLAccess();
            ArrayList<String[]> histories = data_table.list_sell_histories();
            
            for(int i = 0; i < histories.size(); i++){
                Object[] data_list = {
                    i + 1, //order
                    "", // medicine name 
                    "", // medicine name 
                    histories.get(i)[2], // lot no
                    histories.get(i)[3], // selling date
                    histories.get(i)[4], // amount
                    (Float.parseFloat(histories.get(i)[5])/Integer.parseInt(histories.get(i)[4])), // price
                    histories.get(i)[5], // total
                };
                
                ArrayList<String[]> datas = data_table.list_medicine_details(histories.get(i)[1], histories.get(i)[2], "");
                
                switch(datas.get(0)[15]){
                    case "ยาอันตราย":
                        data_list[1] = data_table.get_medicine_name(histories.get(i)[1]);
                        break;
                    case "ยาควบคุมพิเศษ":
                        data_list[2] = data_table.get_medicine_name(histories.get(i)[1]);
                        break;
                }
                
                model.addRow(data_list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        selling = new javax.swing.JButton();
        type11 = new javax.swing.JButton();
        type9 = new javax.swing.JButton();
        type7 = new javax.swing.JButton();
        export = new javax.swing.JButton();
        barcode = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topic.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        topic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topic.setText("รายงานการขาย");

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ลำดับ","ชื่อยาอันตราย" , "ชื่อยาควบคุมพิเศษ", "ครั้งที่ผลิต", "วัน เดือน ปี ที่ขาย" ,"จำนวน/ปริมาณ", "ราคา/หน่วย", "ราคารวม"
            }
        ));
        jScrollPane1.setViewportView(listTable);

        selling.setText("รายการขาย");
        selling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingActionPerformed(evt);
            }
        });

        type11.setText("ข.ย. 11");
        type11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type11ActionPerformed(evt);
            }
        });

        type9.setText("ข.ย. 9");
        type9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type9ActionPerformed(evt);
            }
        });

        type7.setText("ข.ย. 7");
        type7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type7ActionPerformed(evt);
            }
        });

        export.setText("Export excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selling))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(export)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selling)
                    .addComponent(type11)
                    .addComponent(type9)
                    .addComponent(type7)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(export))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UI newUi = new UI();
        newUi.setLocationRelativeTo(this);
        newUi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void type7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type7ActionPerformed
        // TODO add your handling code here:
        report_type = "type7";
        
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
               "ลำดับ","ชื่อยาอันตราย" , "ชื่อยาควบคุมพิเศษ", "เลขที่ของครั้งที่ผลิต", "วัน เดือน ปี ที่ขาย" ,"จำนวน/ปริมาณ", "ราคา/หน่วย", "ราคารวม"
            }
        ));
        
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        
        try {
            MySQLAccess data_table = new MySQLAccess();
            ArrayList<String[]> histories = data_table.list_sell_histories();
            
            for(int i = 0; i < histories.size(); i++){
                Object[] data_list = {
                    i + 1, //order
                    "", // medicine name 
                    "", // medicine name 
                    histories.get(i)[2], // lot no
                    histories.get(i)[3], // selling date
                    histories.get(i)[4], // amount
                    (Float.parseFloat(histories.get(i)[5])/Integer.parseInt(histories.get(i)[4])), // price
                    histories.get(i)[5], // total
                };
                
                ArrayList<String[]> datas = data_table.list_medicine_details(histories.get(i)[1], histories.get(i)[2], "");
                
                switch(datas.get(0)[15]){
                    case "ยาอันตราย":
                        data_list[1] = data_table.get_medicine_name(histories.get(i)[1]);
                        break;
                    case "ยาควบคุมพิเศษ":
                        data_list[2] = data_table.get_medicine_name(histories.get(i)[1]);
                        break;
                }
                
                model.addRow(data_list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_type7ActionPerformed

    private void sellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingActionPerformed
        // TODO add your handling code here:
        report_type = "selling";
        
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ลำดับ" , "ชื่อสินค้า","จำนวน", "จำนวนเงิน", "หมายเหตุ"
            }
        ));
    }//GEN-LAST:event_sellingActionPerformed

    private void type9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type9ActionPerformed
        // TODO add your handling code here:
        report_type = "type9";
        
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
               "ลำดับ","วัน เดือน ปี ที่ซื้อ" , "ชื่อผู้ขาย", "ชื่อยา", "เลขที่ของครั้งที่ผลิต" ,"จำนวน/ปริมาณ", "ราคา/หน่วย", "ราคารวม"
            }
        ));
        
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        
        try {
            MySQLAccess data_table = new MySQLAccess();
            ArrayList<String[]> histories = data_table.list_buy_histories();                
            
            for(int i = 0; i < histories.size(); i++){
                
                ArrayList<String[]> datas = data_table.list_medicine_details(histories.get(i)[1], histories.get(i)[2], "");
                
                Object[] data_list = {
                    i + 1, //order
                    histories.get(i)[3], // buying date
                    datas.get(0)[3], // company name 
                    data_table.get_medicine_name(histories.get(i)[1]), // medicine name
                    histories.get(i)[2], // lot no
                    histories.get(i)[4] + "/" + datas.get(0)[14], // amount/size
                    datas.get(0)[11] + "/" + datas.get(0)[13],   // price/unit
                    (Float.parseFloat(histories.get(i)[4]) * Float.parseFloat(datas.get(0)[11])), // total
                };
                
                
                model.addRow(data_list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_type9ActionPerformed

    private void type11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type11ActionPerformed
        // TODO add your handling code here:
        report_type = "type11";
        
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
               "ลำดับ","วัน เดือน ปี ที่ขาย" , "จำนวน/ ปริมาณ", "ผู้ซื้อ", "เลขที่ของครั้งที่ผลิต" 
            }
        ));

        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        
        try {
            MySQLAccess data_table = new MySQLAccess();
            ArrayList<String[]> histories = data_table.list_sell_histories(barcode.getText());
            
            for(int i = 0; i < histories.size(); i++){
                Object[] data_list = {
                    i + 1, //order
                    histories.get(i)[3], // selling date
                    histories.get(i)[4], // amount/size
                    "",
                    histories.get(i)[2],
                };
                
                model.addRow(data_list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_type11ActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        System.out.println("Excel exporting . . .");
        System.out.println("report type: " + report_type);
        try {
            switch(report_type) {
                case "type7":
                    exportToExcel(listTable,"D:\\reports\\templates\\7_template.xls", "D:\\reports\\7\\1.xls");
                    break;
                case "type9":
                    exportToExcel(listTable,"D:\\reports\\templates\\9_template.xls", "D:\\reports\\9\\1.xls");
                    break;
                case "type11":
                    String medicine_name = "none";
                    try {
                        MySQLAccess medicine_db = new MySQLAccess();
                        medicine_name = medicine_db.get_medicine_name(barcode.getText());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    if(!medicine_name.equals("none")) {
                        exportToExcel(listTable,"D:\\reports\\templates\\11_template.xls", "D:\\reports\\11\\1.xls");
                    } 
                    break;
                case "selling":                    
                    exportToExcel(listTable,"D:\\reports\\templates\\10_template.xls", "D:\\reports\\10\\1.xls");
                    break; 
            }
            
        } catch (IOException e) {
            e.getMessage();
        } catch (BiffException | WriteException ex) {
            Logger.getLogger(Reminder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exportActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        
        try {
            MySQLAccess data_table = new MySQLAccess();
            ArrayList<String[]> histories = data_table.list_sell_histories(barcode.getText());
            
            for(int i = 0; i < histories.size(); i++){
                Object[] data_list = {
                    i + 1, //order
                    histories.get(i)[3], // selling date
                    histories.get(i)[4], // amount/size
                    "",
                    histories.get(i)[2],
                };
    
                model.addRow(data_list);
            }

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(data_table.list_lot(barcode.getText())));
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_barcodeActionPerformed

    public void exportToExcel(javax.swing.JTable table, String import_file, String export_file) throws IOException, BiffException, WriteException {
        System.out.println("Write Start");
        
        Workbook existingWorkbook = Workbook.getWorkbook(new File(import_file));
        System.out.println("Test1.2");
        WritableWorkbook workbook = Workbook.createWorkbook(new File(export_file),existingWorkbook);
        System.out.println("Test1.1");
        WritableSheet sheet = workbook.getSheet("Sheet1");
        
        //Label label = new Label(1, 1, "สวัสดี"); 
        //sheet.addCell(label); 

        //jxl.write.Number number = new jxl.write.Number(2, 2, 3.1459); 
        //sheet.addCell(number);
        
        //table.getValueAt(0, 0);
        System.out.println("Test1");
        workbook.write(); 
        workbook.close();
        existingWorkbook.close();
        System.out.println("Successfully write");
       //System.out.println("Successfully write" + table.getValueAt(0, 0));
      
        /*
       WritableWorkbook wworkbook;
      wworkbook = Workbook.createWorkbook(new File("D:/Projects/Paii_Project/out.xls"));
      WritableSheet wsheet = wworkbook.createSheet("First Sheet", 0);
      Label label = new Label(0, 2, "A label record");
      wsheet.addCell(label);
      jxl.write.Number number = new jxl.write.Number(3, 4, 3.1459); 
      wsheet.addCell(number);
      wworkbook.write();
      wworkbook.close();

      Workbook workbook = Workbook.getWorkbook(new File("D:/Projects/Paii_Project/out.xls"));
      Sheet sheet = workbook.getSheet(0);
      Cell cell1 = sheet.getCell(0, 2);
      System.out.println(cell1.getContents());
      Cell cell2 = sheet.getCell(3, 4);
      System.out.println(cell2.getContents());
      workbook.close();
        */
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JButton export;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listTable;
    private javax.swing.JButton selling;
    private javax.swing.JLabel topic;
    private javax.swing.JButton type11;
    private javax.swing.JButton type7;
    private javax.swing.JButton type9;
    // End of variables declaration//GEN-END:variables
}
