/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Napapol
 */
public class Sell extends javax.swing.JFrame {

    
    private int front_amout = 0;
    private int back_amout = 0;
    private ArrayList<int[]> medicines_data = new ArrayList<int[]>();
    private int[] medicine_data = new int[3];
    private boolean can_add = true;
    private float pack_price;
    private int pack_amount;
    
    PrinterService printerService = new PrinterService();
    /**
     * Creates new form Sell
     */
    public Sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        medicine_code = new javax.swing.JTextField();
        barcode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        company_name = new javax.swing.JTextField();
        medicine_name = new javax.swing.JTextField();
        report_1 = new javax.swing.JLabel();
        barcode_err = new javax.swing.JLabel();
        lotList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        addMore = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        discount_type = new javax.swing.JComboBox<>();
        report_2 = new javax.swing.JLabel();
        finishedButton = new javax.swing.JButton();
        staff_code = new javax.swing.JTextField();
        removeSellList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("รายการสินค้า (ขาย)");

        jLabel6.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel6.setText("Lot ที่");

        jLabel5.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel5.setText("ชื่อบริษัท");

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        medicine_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_codeActionPerformed(evt);
            }
        });

        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel9.setText("ราคา");

        jLabel2.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel2.setText("บาร์โค๊ด");

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel10.setText("จำนวน");

        unit.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        unit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit.setText("หน่วย");

        total.setEnabled(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel4.setText("รหัส");

        jLabel3.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel3.setText("ชื่อยา");

        jLabel12.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel12.setText("ราคารวม");

        company_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_nameActionPerformed(evt);
            }
        });

        medicine_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_nameActionPerformed(evt);
            }
        });

        report_1.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        report_1.setForeground(new java.awt.Color(255, 51, 51));
        report_1.setText("สินค้าลอตนี้หน้าร้านเหลืออีก ... หน่วย || กรุณาหยิบสินค้าเพิ่ม");

        barcode_err.setFont(new java.awt.Font("Cordia New", 0, 20)); // NOI18N
        barcode_err.setForeground(new java.awt.Color(255, 0, 51));
        barcode_err.setText("*");

        lotList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lotList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotListActionPerformed(evt);
            }
        });

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "บาร์โค๊ด", "ลอตที่", "ชื่อยา", "จำนวน(หน่วย)", "ราคา", "ส่วนลด", "รวม"

            }
        ));
        jScrollPane1.setViewportView(listTable);

        addMore.setText("ซื้อเพิ่ม");
        addMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreActionPerformed(evt);
            }
        });

        jButton3.setText("เริ่มใหม่");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jLabel13.setText("ส่วนลด");

        discount.setEnabled(false);
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        discount_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "บาท", "%" }));
        discount_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount_typeActionPerformed(evt);
            }
        });

        report_2.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        report_2.setForeground(new java.awt.Color(255, 51, 51));
        report_2.setText("สินค้าลอตนี้ยังเหลืออยู่ที่หลังร้าน อีก ... หน่วย และ ลอตอื่นๆ อีก ... หน่วย");

        finishedButton.setText("เสร็จสิ้น");
        finishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedButtonActionPerformed(evt);
            }
        });

        staff_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_codeActionPerformed(evt);
            }
        });

        removeSellList.setText("เอาออก");
        removeSellList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSellListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report_1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lotList, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(medicine_code, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(barcode)
                                            .addComponent(medicine_name, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                    .addComponent(company_name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discount_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barcode_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(329, 329, 329))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(staff_code)
                                .addContainerGap())))
                    .addComponent(report_2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(11, 11, 11)
                                            .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addMore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeSellList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finishedButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcode_err))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medicine_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medicine_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(company_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lotList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(report_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(report_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMore)
                    .addComponent(jButton3)
                    .addComponent(finishedButton)
                    .addComponent(removeSellList))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void medicine_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_codeActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
        System.out.print(evt.getActionCommand());
        barcode_err.setText("");
        
        try {
            MySQLAccess db = new MySQLAccess();
            medicine_name.setText(db.get_medicine_name(evt.getActionCommand()));
            
            if( medicine_name.getText().equals("none") ) barcode_err.setText("*รายการนี้ไม่มีอยู่ในฐานข้อมูล");
            
            if(db.list_lot(evt.getActionCommand()).length > 0 && !db.list_lot(evt.getActionCommand())[0].isEmpty()) { 
                lotList.setModel(new javax.swing.DefaultComboBoxModel<>(db.list_lot(evt.getActionCommand())));
                amount.requestFocus();
                amount.setText("1");
            } else {
                lotList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
                barcode_err.setText("*ไม่มีสินค้าในสต๊อก");
            }
            
            ArrayList<String[]> datas = db.list_medicine_details(evt.getActionCommand(), "" ,"exp_date");
            
            int front_1 = 0;
            int back_1 = 0;
            int front_2 = 0;
            int back_2 = 0;
            
            for(int i = 0; i < datas.size(); i++){
                if(datas.get(i)[4].equals(lotList.getSelectedItem().toString())){
                    medicine_data[0] = Integer.parseInt(datas.get(i)[0]);
                    medicine_data[1] = Integer.parseInt(datas.get(i)[6]);
                    medicine_data[2] = Integer.parseInt(datas.get(i)[10]);
                    medicine_code.setText(datas.get(i)[2]);
                    company_name.setText(datas.get(i)[3]);
                    price.setText(datas.get(i)[9]);
                    total.setText(datas.get(i)[9]);
                    unit.setText(datas.get(i)[11]);
                    front_1 = Integer.parseInt(datas.get(i)[6]);
                    back_1 = Integer.parseInt(datas.get(i)[5]);
                    pack_amount = Integer.parseInt(datas.get(i)[17]);
                    pack_price = Float.parseFloat(datas.get(i)[18]);
                } else {
                    front_2 += Integer.parseInt(datas.get(i)[6]);
                    back_2 += Integer.parseInt(datas.get(i)[5]);
                }
            }
            
            front_amout = front_1;
            back_amout = back_1;
            
            if (front_1 > 0) {
                report_1.setText("สินค้าลอตนี้หน้าร้านเหลืออีก " + front_1 +"  " + unit.getText());
                can_add =  true;
            } else {
                can_add =  false;
                if ( back_1 > 0) {
                    report_1.setText("ไม่มีสินค้านี้ที่หน้าร้าน");
                } else if ( (front_2 + back_2) > 0 ) {
                    report_1.setText("สินค้าลอตนี้หมด กรุณาเลือกนี้จากลอตอื่นๆ");
                } else {
                    report_1.setText("สินค้าลอตนี้หมด");
                }
            }
            report_2.setText("สินค้าลอตนี้ยังเหลืออยู่ที่หลังร้าน อีก " + back_1 +"  " + unit.getText() + " และ ลอตอื่นๆ อีก " + (front_2 + back_2) +"  " + unit.getText());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_barcodeActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void company_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company_nameActionPerformed

    private void medicine_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_nameActionPerformed

    private void lotListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotListActionPerformed
        // TODO add your handling code here:
        
        System.out.print("Lot is changed");
        try {
            MySQLAccess db = new MySQLAccess();
            
            ArrayList<String[]> datas = db.list_medicine_details(barcode.getText(), "" ,"exp_date");
            
            int front_1 = 0;
            int back_1 = 0;
            int front_2 = 0;
            int back_2 = 0;
            
            for(int i = 0; i < datas.size(); i++){
                if(datas.get(i)[4].equals(lotList.getSelectedItem().toString())){
                    medicine_data[0] = Integer.parseInt(datas.get(i)[0]);
                    medicine_data[1] = Integer.parseInt(datas.get(i)[6]);
                    medicine_data[2] = Integer.parseInt(datas.get(i)[10]);
                    medicine_code.setText(datas.get(i)[2]);
                    company_name.setText(datas.get(i)[3]);
                    price.setText(datas.get(i)[9]);
                    unit.setText(datas.get(i)[11]);
                    front_1 = Integer.parseInt(datas.get(i)[6]);
                    back_1 = Integer.parseInt(datas.get(i)[5]);
                    pack_amount = Integer.parseInt(datas.get(i)[17]);
                    pack_price = Float.parseFloat(datas.get(i)[18]);
                } else {
                    front_2 += Integer.parseInt(datas.get(i)[6]);
                    back_2 += Integer.parseInt(datas.get(i)[5]);
                }
            }
            
            front_amout = front_1;
            back_amout = back_1;
            
            if (front_1 > 0) {
                report_1.setText("สินค้าลอตนี้หน้าร้านเหลืออีก " + front_1 +"  " + unit.getText());
                can_add =  true;
            } else {
                can_add =  false;
                if ( back_1 > 0) {
                    report_1.setText("ไม่มีสินค้านี้ที่หน้าร้าน");
                } else if ( (front_2 + back_2) > 0 ) {
                    report_1.setText("สินค้าลอตนี้หมด กรุณาเลือกนี้จากลอตอื่นๆ");
                } else {
                    report_1.setText("สินค้าลอตนี้หมด");
                }
            }
            report_2.setText("สินค้าลอตนี้ยังเหลืออยู่ที่หลังร้าน อีก " + back_1 +"  " + unit.getText() + " และ ลอตอื่นๆ อีก " + (front_2 + back_2) +"  " + unit.getText());
            amount.setText("1");
            total.setText((Float.parseFloat(price.getText()) * Integer.parseInt(amount.getText()))+"");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lotListActionPerformed

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        // TODO add your handling code here:
        if("0123456789".contains(evt.getKeyChar()+"")){
            System.out.println("Corrected!!!!!");
        } 
    }//GEN-LAST:event_amountKeyTyped

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        System.out.println(front_amout);
        float total_price = 0f;
        float total_price_with_no_discount = 0f;
        int amount_ = Integer.parseInt(evt.getActionCommand());
        float price_ = Float.parseFloat(price.getText());
        if ( amount_ <= front_amout ){
            total_price_with_no_discount = price_ * amount_;
            int pack_num = amount_/pack_amount;
            total_price =  (pack_num * pack_price) + ((amount_%pack_amount) * price_);
            total.setText((total_price) +"");
            discount.setText(total_price_with_no_discount - total_price + "");
            staff_code.requestFocus();
        } else {
            report_1.setText("สินค้าหน้าร้านมีเพียง" + front_amout + " กรุณาหยิบสินค้าเพิ่ม คงเหลืออยู่ที่หลังร้านอีก " + back_amout + " " + unit.getText());
        }
    }//GEN-LAST:event_amountActionPerformed

    private void addMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreActionPerformed
        // TODO add your handling code here:
        if ( barcode_err.getText().isEmpty() && !amount.getText().isEmpty() && !total.getText().isEmpty() && can_add){
            DefaultTableModel model = (DefaultTableModel) listTable.getModel();

            Object[] data_list = {
                barcode.getText(),
                lotList.getSelectedItem().toString(),
                medicine_name.getText(),
                amount.getText() + "(" + unit.getText() + ")",
                price.getText(),
                discount.getText()+"-"+discount_type.getSelectedItem(),
                total.getText()
            };
            medicine_data[1] -= Integer.parseInt(amount.getText());
            medicine_data[2] -= Integer.parseInt(amount.getText());
//            System.out.println(medicine_data[0] + " " + medicine_data[1] + " " + medicine_data[2]);
            int[] temp = new int[3];
            temp[0] = medicine_data[0];
            temp[1] = medicine_data[1];
            temp[2] = medicine_data[2];
            medicines_data.add(temp);
            
            model.addRow(data_list);  
            
            barcode.setText("");
            medicine_name.setText("");
            medicine_code.setText("");
            company_name.setText("");
            lotList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
            report_1.setText("กรุณาเลือกสินค้า");
            report_2.setText("");
            price.setText("");
            amount.setText("");
            total.setText("");
            discount.setText("");
        }
        
        for(int i = 0; i < medicines_data.size(); i++) {
            System.out.println(medicines_data.get(i)[0] + " " + medicines_data.get(i)[1] + " " + medicines_data.get(i)[2]);
        }
        
    }//GEN-LAST:event_addMoreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        model.setNumRows(0);
        medicines_data.clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
        float tempDiscount = Float.parseFloat(discount.getText());
        float tempTotal = Float.parseFloat(price.getText()) * Integer.parseInt(amount.getText());
        
        if (discount_type.getSelectedItem().toString().equals("%")) { 
            tempDiscount = tempTotal * (tempDiscount / 100);
        }
        total.setText((tempTotal - tempDiscount) + "");
    }//GEN-LAST:event_discountActionPerformed

    private void finishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        try {
            MySQLAccess db = new MySQLAccess();
            // barcode, lot, current_date, amout, total, discount
            for ( int i = 0; i < model.getRowCount(); i++){
                db.insert_sell_histories(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString(), 
                        new java.sql.Date(new Date().getTime()), Integer.parseInt(model.getValueAt(i, 3).toString().substring(0, model.getValueAt(i, 3).toString().indexOf("("))), 
                        Float.parseFloat(model.getValueAt(i, 6).toString()), model.getValueAt(i, 5).toString());
            }
            
            for (int i = 0; i < medicines_data.size(); i++) {
                int[] medicine_temp = medicines_data.get(i);
//                System.out.println(medicine_temp[0] + " " + medicine_temp[1] + " " + medicine_temp[2]);
                db.sell_medicine(medicine_temp[0], medicine_temp[1], medicine_temp[2]);
            }
            medicines_data.clear();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
//        printerService.pustAl(getList());
//        printerService.setdetail();
//        printerService.printString("EPSON TM-T88IV Receipt");
        model.setNumRows(0);
    }//GEN-LAST:event_finishedButtonActionPerformed

    private void discount_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount_typeActionPerformed
        // TODO add your handling code here:
        float tempDiscount = Float.parseFloat(discount.getText());
        float tempTotal = Float.parseFloat(price.getText()) * Integer.parseInt(amount.getText());
        
        if (discount_type.getSelectedItem().toString().equals("%")) { 
            tempDiscount = tempTotal * (tempDiscount / 100);
        }
        total.setText((tempTotal - tempDiscount) + "");
    }//GEN-LAST:event_discount_typeActionPerformed

    private void staff_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_codeActionPerformed
        // TODO add your handling code here:
//        System.out.println(evt.getActionCommand());
        if(evt.getActionCommand().equalsIgnoreCase("minapapol789")) {
            System.out.println(evt.getActionCommand());
            discount.enable();
            discount.requestFocus();
        }
    }//GEN-LAST:event_staff_codeActionPerformed

    private void removeSellListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSellListActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selRow = listTable.getSelectedRow();
        System.out.println(selRow + "");
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
        
        model.removeRow(selRow);
        
    }//GEN-LAST:event_removeSellListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }
    
    public ArrayList<String> getList(){
        ArrayList<String> temp = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) listTable.getModel();
            // name,amount,price
            for(int i = 0; i < model.getRowCount(); i++){
                temp.add(model.getValueAt(i, 2).toString() + "," + model.getValueAt(i, 3).toString().substring(0, model.getValueAt(i, 3).toString().indexOf("(")) + "," + model.getValueAt(i, 4).toString() + "," +model.getValueAt(i, 5).toString().split("-")[0]+ "," + model.getValueAt(i, 5).toString().split("-")[1]);
                System.out.println(temp.get(i));
            }
        return temp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMore;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField barcode;
    private javax.swing.JLabel barcode_err;
    private javax.swing.JTextField company_name;
    private javax.swing.JTextField discount;
    private javax.swing.JComboBox<String> discount_type;
    private javax.swing.JButton finishedButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listTable;
    private javax.swing.JComboBox<String> lotList;
    private javax.swing.JTextField medicine_code;
    private javax.swing.JTextField medicine_name;
    private javax.swing.JTextField price;
    private javax.swing.JButton removeSellList;
    private javax.swing.JLabel report_1;
    private javax.swing.JLabel report_2;
    private javax.swing.JTextField staff_code;
    private javax.swing.JTextField total;
    private javax.swing.JLabel unit;
    // End of variables declaration//GEN-END:variables
}
